version: '3'
services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "demo_shop_db"
      POSTGRES_USER: "raya_user"
      POSTGRES_PASSWORD: "bebka1963*"